### ISSUE TITLE
ssh times out when trying to connect dropbear

### ISSUE THREAD

**Issue by 2600box** [Val/dedibox_fully_encrypted_debian_install#2]
have followed the guide using an online.net instance. using the same partition map, when it comes time to connect to dropbear, the connection times out. have tried specifying port for dropbear without result

have tried using debian 8 and debian 9 as base installation, with stretch as target. 

it appears to be related to networking in initramfs.conf and have tried the following:
DEVICE=enp0s20f0
DEVICE=enp0s20
DEVICE=eth0

a few outputs from debian 9 to aid with troubleshooting:

```
# sed -e "s|^\(DEVICE=\).*$|\1${id_net_name_path}|"   -i /etc/initramfs-tools/initramfs.conf
sed: -e expression #1, char 29: unterminated `s' command
```

```
# egrep -v '^(#|$)' /etc/initramfs-tools/initramfs.conf
MODULES=most
BUSYBOX=auto
KEYMAP=n
COMPRESS=gzip
DEVICE=enp0s20f0
NFSROOT=auto
```

```
# echo $(udevadm info -e | grep -A 9 ^P.*/net/ |grep ID_NET_NAME_PATH |cut -f2 -d=)
enp0s20f0 enp0s20f1
```

```
# ip link show |egrep -v lo
2: enp0s20f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 00:16:af:0b:81:3d brd ff:ff:ff:ff:ff:ff
3: enp0s20f1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:16:af:0b:81:3e brd ff:ff:ff:ff:ff:ff
```

**Comment by 2600box** [comment]
by adjusting the variable `$ID_NET_NAME_PATH` to pick up just one interface, the errors with sed are resolved. but i still cannot connect to dropbear...

I added `-m1` to grep like this `id_net_name_path=\
$(udevadm info -e | grep -A 9 ^P.*/net/ |grep -m1 ID_NET_NAME_PATH |cut -f2 -d=)` then I get just `enp0s20f0`

but no dice on connecting to the initramfs dropbear...

**Comment by 2600box** [comment]
ok. this gets weird. 

i have been trying different variables and twice I got it to work. i was able to connect with ssh, input my passwords and it continued, then i connected again and all was well. in my greed/curiosity, I went back to install the same again, using the exact same variables, and it doesn't work.

once i changed some grub settings (turned off quiet and set console). the other time I set the port to 2222. both times I had used the fixed network interface name command.

if i manage to succeed again, i'm just going to just stick with it. or at least test rebooting, which i did not do.

**Comment by 2600box** [comment]
this is crazy frustrating.

i did an install. couldn't connect to dropbear. then i went off and did other things for an hour or so. came back and tried to connect. and it worked. 

i logged in. all was good. so i did a reboot `# sudo reboot` and i could not connect. i let it wait for over an hour and still nothing. 

so we have a known good install that is confirmed to have worked once, but won't connect after a reboot. what the?!

what could possibly cause that kind of behaviour?

**Comment by 2600box** [comment]
ok. i have narrowed it down to grub.

i can get it to reliably boot by enabling console access like so:
```
GRUB_CMDLINE_LINUX="ip=MY_IP_ADDR::MY_DEFAULT_GW:MY_NETMASK::eth0:none console=ttyS1,9600"
GRUB_CMDLINE_LINUX_DEFAULT=""
GRUB_TERMINAL=serial
GRUB_SERIAL_COMMAND="serial --unit=1 --speed=9600 --word=8 --parity=no --stop=1"

```

this seems to indicate a timeout issue, so i tried removing that stuff and only adding `GRUB_RECORDFAIL_TIMEOUT` but it still doesn't boot.

with default grub configuration - almost always fails to boot
with serial console - always works. i don't need to have the console open, either.

any idea how to turn off serial access and still have grub boot?

**Comment by 2600box** [comment]
monitoring the console, I can see that without the networking line, grub struggles with dhcp and eventually catches dhcp for the secondary (internal) interface and ignores the primary. so i can't connect. specifying the correct interface works, but only when the serial console is enabled. if i just add the networking line to the default, it still fails, but i can't see why - obviously.

this is the config I am running now. is there any security risk here? would like to see yours.

```
GRUB_CMDLINE_LINUX="ip=:::::enp0s20f0:dhcp"
GRUB_CMDLINE_LINUX_DEFAULT=""
GRUB_TERMINAL=serial
GRUB_SERIAL_COMMAND="serial --unit=1 --speed=9600 --word=8 --parity=no --stop=1"
```

**Comment by ink0gnito** [comment]
Hey 2600box i have the same issue with dropbear. :/
Maybe Val has a solution.

**Comment by 2600box** [comment]
i had two issues:

1) my box has two NIC, so I had to make sure to only pass your primary interface to `initramfs.conf` and `/etc/network/interfaces.d/01_primary` when following @Val steps

2) grub doesn't work in the default config, I needed to specify the network config and `serial` for `GRUB_TERMINAL`

it would be great to see what @Val has in his `/etc/default/grub`
