### ISSUE TITLE
After dropbear encrypt no network

### ISSUE THREAD

**Issue by ink0gnito** [Val/dedibox_fully_encrypted_debian_install#3]
I follow this guide and try to encrypt the dedibox.
After that i made a reboot on the online.net console.
I connect to dropbear, execute /sbin/start_dm_crypt and entered the passwords and logged out.
But after that i can not connect to the server by ssh.

In the online.net console i see a network failure.
![online net](https://user-images.githubusercontent.com/20971485/28887539-ca79a9f8-77bd-11e7-9d87-5d0a1b15706c.png)

Has anybody a solution for me?

**Comment by 2600box** [comment]
what is in your `/etc/network/interfaces.d/01_primary` ? 
what is the result of `ip a` ?

Do they match?

**Comment by Val** [comment]
@2600box, @ink0gnito does it work now?

If "Your server port is off" means closed port there is an IP.
If not, you should get a "no route to host".
