### ISSUE TITLE
sed script changes nothing on sda.sfdisk file

### ISSUE THREAD

**Issue by Exception0815** [Val/dedibox_fully_encrypted_debian_install#8]
Hello,

it seems like the sed script changes nothing in my case on the sda.sfdisk file during the "Change encrypted partition types" section. I think the partition type of the large partition needs to be changed.
Can you please tell me what needs to be done so I can edit the file manually?

Thank you very much!

![grafik](https://user-images.githubusercontent.com/30669079/29241208-87b06804-7f75-11e7-9b6b-66f37b3c2118.png)

**Comment by Val** [comment]
@Exception0815 the copy-paste on your system may have change some characters like the single quote to another unicode one. You can manually replace `type=82` or `type=83` by `type=da` on both lines but the first wich is bootable: `sda1`.
