### ISSUE TITLE
dropbear after reboot not reachable

### ISSUE THREAD

**Issue by ink0gnito** [Val/dedibox_fully_encrypted_debian_install#9]
Hi, thx for your full encrypted dedibox guide on github.
I use it a long without problems.
But yesterday i made an update/upgrade and there are changes with the
dropbear keys.
After i reboot the dedibox i have no access to dropbear and i can not
ping the server.
The server is not reachable.
I have boot the server in rescue mode and mount the crypt sda/sda4.
Unfortunately, I have no idea why the server is not available after the
start.
the only thing I have seen is that the dropbear keys changed after the
update. /etc/dropbear-initramfs
Should i copy the dropbear keys from backup to the server and reboot?
It would be very nice of you if you would give me a hint.

**Comment by ink0gnito** [comment]
update:
I have booted the server in rescue mode, then i mounted /boot and sda3_crypt.
after that i made an 
update-initramfs -u -kall
sync
then i have reboot the server.
dropbear is reachable and i execute /sbin/start_dm_crypt but after that the server did not continue the boot process.
After Hard Reboot on online.net panel the server is also unreachable

**Comment by Val** [comment]
@ink0gnito : boot process after `/sbin/start_dm_crypt` is sometime very long, did you wait at least a few minutes ? When I do reboot my box I leave a `ping` running in another terminal to check server IP availability. Did your box respond to ping after a successful `/sbin/start_dm_crypt` ?

**Comment by ink0gnito** [comment]
Yes i wait few minutes. Normally after i execute /sbin/start_dm_crypt and input the passphrase for sda3 and sda4 the script will continue the boot process and the dropbear shell session canceled automatically.
But after few minutes i can still open a ssh session in dropbear. 
The first session will not be interrupted automatically

**Comment by Val** [comment]
And what's going on ? Does the box respond to ping after a `/sbin/start_dm_crypt` success?

**Comment by ink0gnito** [comment]
The server response the whole time the ping.
After 10 minutes i try to login via ssh but i am only on busybox interface.
Here ist my output from start_dm_crypt

`/sbin/start_dm_crypt 
------------------------------------------------------------------------------
unlocking /data
Enter passphrase for /dev/sda4: 
------------------------------------------------------------------------------
unlocking / & exit
Please unlock disk sda3_crypt: 
cryptsetup (sda3_crypt): set up successfully
------------------------------------------------------------------------------
quit & continue boot? (Y/n)Y
------------------------------------------------------------------------------
sending return on passfifo (try #1)
`

After 30 minutes i stop the script with ctrl c and i get a failure " /sbin/start_dm_crypt: line 38: can't create /lib/cryptsetup/passfifo: Interrupted system call"

**Comment by Val** [comment]
Ok, so you get `quit & continue boot? (Y/n)` another time, try to enter twice to force to continue boot process. It's a `passfifo` problem I think (kernel part).

**Comment by Val** [comment]
If it's that you should have ping break a few times between new IP stack grows up.

**Comment by ink0gnito** [comment]
Hard to believe, but my server is running again.
I booted the server in rescue mode a few times. 
Subsequently i mounted sda1/3/4, then i made a grub-update and an update-initramfs -u -kall with sync.
After the force reboot from console the server was answering und accepted the passphrase.

**Comment by Val** [comment]
Nice ! Happy to hear it.
